export const ROOM = {
  CODE_LENGTH: 6,
  CREATE_LIMIT: 3,
  JOIN_LIMIT: 5,
  GRACE_WINDOW_MS: 5 * 60_000,
  DEFAULT_MAX_PLAYERS: 5,
  CLEANUP_INTERVAL_MS: 60_000,
  EXPIRATION_MINUTES: 60,
  NOTIFICATION_LIMIT: 20,
} as const
